alias: Basement rope light
description: ''
triggers:
  - alias: When a monitored device did something
    trigger: state
    entity_id:
      - scene.basement_rope_lights_blue
      - scene.basement_rope_lights_blue_green
      - scene.basement_rope_lights_carolina_blue
      - scene.basement_rope_lights_fade
      - scene.basement_rope_lights_green
      - scene.basement_rope_lights_in_waves
      - scene.basement_rope_lights_jump
      - scene.basement_rope_lights_light_green
      - scene.basement_rope_lights_light_orange
      - scene.basement_rope_lights_magenta
      - scene.basement_rope_lights_maroon
      - scene.basement_rope_lights_multi_color
      - scene.basement_rope_lights_navy_blue
      - scene.basement_rope_lights_orange
      - scene.basement_rope_lights_pink
      - scene.basement_rope_lights_red
      - scene.basement_rope_lights_red_orange
      - scene.basement_rope_lights_strobe
      - scene.basement_rope_lights_teal
      - scene.basement_rope_lights_twinkle
      - scene.basement_rope_lights_white
      - scene.basement_rope_lights_yellow
    to: null
conditions: []
actions:
  - variables:
      codes:
        asyn fade: 'B30jPhFnAgkCwAMCCQJnoAFACUADQAEBYQbgBQNAF+AHE0APAAkgAQBnIAGACwFnAkADAmcCCSABgAVAF0ADAwkCZwJAB8ADDxGgfSOaCAkC//99I5oIZwI='
        asyn jump: 'BVAjsREjAuABAQJ2AiPgCgECYQZ2IAPgAQcBIwJAD+ANA8AbQAfgCwNAN0AXQAcCYQYjYAMHMqBQI5sIdgI='
        fade: 'B4sjTBFvAiACQANAAUAHQAPgAQEAbyABAWAG4AUDQBXgBxNAD8AXQAfgBQOAAeABI4ALgAcJIAImoIsjpwggAg=='
        in waves: 'B3IjQhFrAjIC4AcD4AUBAXoGwAMAa2ALQAHACwN6BjICwAEEegZrAjIgAQV6BjICMgKACwMyAmsCQA8EegZrAjIgAQN6BjICQAFAB8ADD0CgciPlCDIC//9yI+UIMgI='
        jump: ''
        twinkle: 'BqMjPRFxAiAgAYAF4AkBQBcBfAZAAwBxoAcBIAJAAQF8BkAPQAPgAwsCcQIgIAGAB0AL4AcDASACwBtAB4ADCSACQqCjI5QIcQI='
        strobe: 'B30jXBFoAikCQAPAAeAHCwNoAmsGwAMAKWALBSkCaAJrBkADAClgBwApIAECawZoYAMDKQJoAkALAClgAUAHAWgCgA8CaAIpIAEJawYpAikCaAJrBkADAClgBwf2n30jnAhoAg=='

        down: 'BUIjrBEzAuARAQJ5AjMgAQKABnkgA0AHgANAAcAL4AEHQCPAAwEzAoABAnkCM2ABwAfgAQFAI8ADB1GgQiPgCDMC'
        off: 'BWEjdhFAAuAXAQF6BuAFA0AB4BcT4AcBQC/gAwFAD8ADByegYSOlCEAC'
        on: 'BmkjeRFvAirgDgHAGQJkBm/gBAMAKiAB4AMTACpgAQFvAuALE+ADFwAqIAEAbyABACogAeADKwcHoGkjnQhvAg=='
        up: 'B6EjRRFxAioCwANAAUALQAFAB4ADAXUG4AUDACogAQF1BuABA0ABgA8AcaAHBSoCKgJxAoADASoCgA9AAUATgAELdQZxAnUGKgJ1BioC'

        blue: 'BpojWxF3AifgBAHgBw8EJwJYBnfgBAMAJyAB4AMTAycCdwJAD0AHACfgBAFADwF3AsAbQAfgCwMHB6CaI5QIdwI='
        blue green: 'BYAjaxEkAoABAXEC4AEDQAFAD0ABBHECZwYkIANAB4ADAyQCcQLAC4AHBiQCJAJxAiSgAQFnBkALQANAAYAHQBPAAwMkAnECwAsLZwZxAs+fgCOWCHEC'
        carolina blue: 'BoMjbhFzAiVgAUAHQAPAAUALgAMBYQZAAwAlIAdAAwJzAiUgAUAH4AMDAyUCcwLADwAlYAHAB4ABQBsAJSABQAVAC+ADAwf9n4MjkwhzAg=='
        green: 'Bn0jahFzAirgBAFAD8ADgAEBdgZAAwBzoAcDKgIqAsALQAeAAwAqYAHgAwfgBQsCdgYq4AYD4AETD0CgfSO4CHMC//99I7gIcwI='
        light green: 'BYAjXxE4AuAXAQFuBsADAHNgCwE4AoAHwA8FbgY4AjgCQBMCcwI44AgBgBPAG0AH4AEDQA8JOAI8oIAjqQg4Ag=='
        light orange: 'B4YjuxGHAtEBQAMBRALgDwEBbAbgBQNAK+ADE8ABAmwGhyADAUQCQB/gAwEBbAaAF4ABQAtAAwFEAoADEYcCB6CGI5oIRAL//4YjmghEAg=='
        magenta: 'BYAjahEyAuABAQFjAuALAwJzBjLgBAMBMgLgAxMBYwKAD0AHBzICcwYyAjICgAuAAQVjAnMGYwLgAQcDMgJzBkADAGPgAAcP/5+AI5kIMgL//4AjmQhjAg=='
        maroon: 'BUQjqRE+AuAJAQJ5Aj7gAgEBawbgBQNAAQJrBnkgA0AHAT4CQAGAB4AT4AcBgBsBPgKAB4AjAWsGwAcJPgIIoEQjrwg+Ag=='
        multi color: 'CXkjXBEsAiwCaQKAA+ANAQJvBmngBAMALCABAW8GQAMAaSAH4AUDACxgAYAH4AkFASwC4AcvC28GaQIpoHkjnQhpAg=='
        navy blue: 'BokjWxFlAivgCAGAE8AFAWwG4AUDQBngAxMAKyABwA8BKwJAA+AFAUAbASsCgANAC+AHAwcvoIkjlAgrAg=='
        orange: 'BpEjUxFmAjngFAEDZgJvBkADADmgBwhmAjkCZgJvBjngAAOAAQJmAjkgAUAX4AUBA2YCbwZAAwA5YAcAOSABAm8GZiADQAdAAwlmAgygkSOnCGYC'
        pink: 'BzQjrBFuAhUC4AcDQAHgARMBXwbgBQNAG+ADE8APQAdAA0AbABVgAYAHgA8BbgJAB0ADABUgAQtfBm4CXwZuAl8GbgI='
        red: 'BncjWBFwAizgAAFAC0ADgAEAcCABACwgAQJ8BnDgBAMALCABgBOABwEsAkAD4AMB4AUPgCfgCwcAcGAbB2mgdyPHCCwC'
        red orange: 'B4wjXRFnAg4C4AcDAg4CZyABQAVAAwFdBuAFA+AHE0APQANAJwAOIAEAZyABQAXAA0AXQANAD0AH4AcDBxugjCOiCGcC'
        teal: 'CoIjXREnAicCeQIn4AQBQA/AAwQnAmYGeSADwAcCeQInIAFAB+ADAwAnoAFAEwAn4AQBgA9AF0ADACcgAUAH4AMDB/mfgiOeCCcC'
        white: 'Bp4jXhFoAhcgAQBoIAEAFyABAGggAUAF4AMDAVYG4AUDQBvgBxNADwAXIAFABQBoIAFABQAXIAEAaCABABcgAQBoIAFAI+ALAwcFoJ4jfAhoAg=='
        yellow: 'BmsjfRFsAjDgFgEBcgZAAwBsIAeAAwAwIAHAC0AHADBgAQFsAkALQAMAMOAGAUATQAMAMKABAXIGQAMJbAJyBmwCcgZsAg=='
      event_type: '{{ trigger.to_state.attributes.event_type }}'
      entity_id: '{{ trigger.to_state.entity_id }}'
      entity_state: '{{ trigger.to_state.state }}'
      scene: >-
        {{ entity_id[27:] | regex_replace(find='_', replace=' ', ignorecase=True)  }}
      code_to_send: '{{ codes[scene] }}'
      # payload_obj: { 'ir_code_to_send': '{{ code_to_send }}' }
      payload: >
        {"ir_code_to_send":
        "{{ code_to_send }}"
        }
    alias: Define vars
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ code_to_send != '' }}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              evaluate_payload: false
              qos: 0
              retain: false
              payload: '{{ payload }}'
              topic: zigbee2mqtt/Basement rope lights/set
            alias: publish
mode: single
